start-at-login = true 

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'


exec-on-workspace-change = [
  '/bin/bash', 
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focus-changed = [
"move-mouse window-lazy-center",
  'exec-and-forget sketchybar --trigger front_app_switched'
]

[gaps]
inner.horizontal = 20
inner.vertical = 10
outer.left = 20 
outer.bottom = 20
outer.top = 50 
outer.right = 20

[mode.main.binding]
ctrl-shift-cmd-f = 'fullscreen'

ctrl-shift-cmd-r = 'layout horizontal vertical' # [R]otate
ctrl-shift-cmd-s = 'layout tiles accordion' # [S]tacked
ctrl-shift-cmd-a = 'layout tiling' # [A]ttach
ctrl-shift-cmd-d = 'layout floating' # [D]etach

ctrl-shift-cmd-h = ['focus left', 'move-mouse window-lazy-center']
ctrl-shift-cmd-j = ['focus down', 'move-mouse window-lazy-center']
ctrl-shift-cmd-k = ['focus up', 'move-mouse window-lazy-center']
ctrl-shift-cmd-l = ['focus right', 'move-mouse window-lazy-center']

ctrl-shift-cmd-alt-h = 'move left'
ctrl-shift-cmd-alt-j = 'move down'
ctrl-shift-cmd-alt-k = 'move up'
ctrl-shift-cmd-alt-l = 'move right'

ctrl-shift-cmd-left = 'join-with left'
ctrl-shift-cmd-down = 'join-with down'
ctrl-shift-cmd-up = 'join-with up'
ctrl-shift-cmd-right = 'join-with right'

ctrl-shift-cmd-g = 'flatten-workspace-tree' # [G]round

ctrl-shift-cmd-0 = 'balance-sizes' 
ctrl-shift-cmd-minus = 'resize height -100'
ctrl-shift-cmd-equal = 'resize height +100'
ctrl-shift-cmd-comma = 'resize width -100'
ctrl-shift-cmd-period = 'resize width +100'

ctrl-shift-cmd-alt-y = 'workspace Y'
ctrl-shift-cmd-alt-u = 'workspace U'
ctrl-shift-cmd-alt-i = 'workspace I'
ctrl-shift-cmd-alt-o = 'workspace O'
ctrl-shift-cmd-alt-p = 'workspace P'
ctrl-shift-cmd-alt-quote = 'workspace qt'
ctrl-shift-cmd-alt-semicolon = 'workspace sc'
ctrl-shift-cmd-alt-backslash = 'workspace bs'

ctrl-shift-cmd-y = 'move-node-to-workspace Y'
ctrl-shift-cmd-u = 'move-node-to-workspace U'
ctrl-shift-cmd-i = 'move-node-to-workspace I'
ctrl-shift-cmd-o = 'move-node-to-workspace O'
ctrl-shift-cmd-p = 'move-node-to-workspace P'
ctrl-shift-cmd-quote = 'move-node-to-workspace qt'
ctrl-shift-cmd-semicolon = 'move-node-to-workspace sc'
ctrl-shift-cmd-backslash = 'move-node-to-workspace bs'

ctrl-shift-cmd-alt-6 = 'workspace-back-and-forth'

ctrl-shift-cmd-m = [ 'focus-monitor --wrap-around next', 'move-mouse window-lazy-center' ]
ctrl-shift-cmd-alt-m = 'move-node-to-monitor --wrap-around next'
ctrl-shift-cmd-alt-w = 'move-workspace-to-monitor --wrap-around next'


alt-tab = 'workspace-back-and-forth'

[workspace-to-monitor-force-assignment]

Y = 'main'
U = 'main'
I = 'main'
O = 'main'
P = 'main'
'qt' = ['LG ULTRAWIDE', 'secondary', 'main']
'sc' = ['LG ULTRAWIDE', 'secondary', 'main']
'bs' = ['LG ULTRAWIDE', 'secondary', 'main']

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'              
run = ['move-node-to-workspace bs']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace bs']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['move-node-to-workspace bs']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace P']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
if.app-name-regex-substring = 'zoom.us'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = ['move-node-to-workspace U']
